### ISSUE TITLE
Operations params are not defined

### ISSUE THREAD

**Issue by jamiehannaford** [rackerlabs/wadl2swagger#8]
Right now it feels that params are not consistently defined for HTTP operations. Take the `/v2/{tenant_id}/servers` path, for example, which has a `GET` and `POST`:

``` yaml
  "/v2/{tenant_id}/servers":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The tenant ID in a multi-tenancy cloud.
    get:
      operationId: listServers
      summary: List servers
      description: |
        Lists IDs, names, and links for all servers.
      produces:
      - application/json
      parameters:
      - name: changes-since
        required: false
        in: query
        type: string
        format: date-time
        description: |
          A time/date stamp for when the server last changed status.
      - name: image
        required: false
        in: query
        type: string
        format: uri
        description: |
          Name of the image in URL format.
      - name: flavor
        required: false
        in: query
        type: string
        format: uri
        description: |
          Name of the flavor in URL format.
      - name: name
        required: false
        in: query
        type: string
        description: |
          Name of the server as a string; can be queried with regular expressions. Realize that ?name=bob returns both bob and bobb. If you need to match bob only, you can use a regular expression matching the syntax of the underlying database server implemented for Compute (such as MySQL or PostgreSQL).
      - name: marker
        required: false
        in: query
        type: string
        description: |
          UUID of the server at which you want to set a marker.
      - name: limit
        required: false
        in: query
        type: integer
        description: |
          Integer value for the limit of values to return.
      - name: status
        required: false
        in: query
        type: string
        description: |
          Value of the status of the server so that you can filter on "ACTIVE" for example.
      - name: host
        required: false
        in: query
        type: string
        description: |
          Name of the host as a string.
    post:
      operationId: createServer
      summary: Create server
      description: |
        Creates a server.
      produces:
      - application/json
```

The `GET` has multiple params, whereas the `POST` (which actually uses a lot of params) has none defined. This makes it hard for an SDK to rely on these Swagger files.

I know you said you skip param definitions if they do not produce valid json-schema, but could we have a flag that provides the option?

**Comment by maxlinc** [comment]
I'd prefer to either not call data that belongs in a request/response body a "parameter" at all, or to refer to them specifically as "body parameters". I'd rather refer to them as elements within a "schema" or "model".

Note the "style" while looking at operations on api.rackspace.com. You should notice that what is missing are parameters with a style of "plain". The get operation has many parameters with other styles (URI, query, etc), and they all show up in Swagger. The post operation has many "plain" parameters but just one non-plain parameter - `tenant_id`. You can see that parameter is properly defined in Swagger by previewing in the Swagger editor:

![screen shot 2015-02-04 at 9 40 35 am](https://cloud.githubusercontent.com/assets/896878/6042392/58943594-ac52-11e4-98ea-07210894fe09.png)

What if I did give you access to all of the "plain" parameters as they show up on api.rackspace.com? You still wouldn't be able to use it reliably for code generation. Although those parameters are *should* correspond to a schema they are essentially freeform documentation that hasn't been validated to be complete or accurate. Here's an example I spotted just on the Create Server operation. The api docs say this:

| parameter | style | type | description |
|------------------------|--------|---------------|---------------------------------------|
| personality (Optional) |  plain | csapi:string  | File path and contents (text only) to inject into the server at launch. The maximum size of the file path data is 255 bytes. The maximum limit refers to the number of bytes in the decoded data and not the number of characters in the encoded data. |

Sounds good, right? But look at the sample:

```json
"personality": [
            {
                "path": "/etc/banner.txt",
                "contents": "ICAgICAgDQoiQSBjbG91ZCBkb2VzIG5vdCBrbm93IHdoeSBpdCBtb3ZlcyBpbiBqdXN0IHN1Y2ggYSBkaXJlY3Rpb24gYW5kIGF0IHN1Y2ggYSBzcGVlZC4uLkl0IGZlZWxzIGFuIGltcHVsc2lvbi4uLnRoaXMgaXMgdGhlIHBsYWNlIHRvIGdvIG5vdy4gQnV0IHRoZSBza3kga25vd3MgdGhlIHJlYXNvbnMgYW5kIHRoZSBwYXR0ZXJucyBiZWhpbmQgYWxsIGNsb3VkcywgYW5kIHlvdSB3aWxsIGtub3csIHRvbywgd2hlbiB5b3UgbGlmdCB5b3Vyc2VsZiBoaWdoIGVub3VnaCB0byBzZWUgYmV5b25kIGhvcml6b25zLiINCg0KLVJpY2hhcmQgQmFjaA=="
            }
        ]
```

The "personality" isn't a string! It's an array of objects that each contain a "path" and "contents". So some of the parameters are have improperly defined types.

Here's another example, again from the same service:

| parameter | style | type | description |
|------------------------|--------|---------------|---------------------------------------|
| delete_on_termination | plain | csapi:string | To delete the boot volume when the server stops, specify `true`. Otherwise, specify `false`. |


Now, before we look at the example, let's just break down what the documentation appears to say.

We don't know:
- It's location within the document hierarchy. Presumably it's an element off the root.

We do know:
- It is a required parameter (or it would be marked as `(Optional)`)
- It defined as a string, but the description actually makes it look like a boolean.

Here's the example:

```json
        "block_device_mapping_v2": [
            {
                "device_name": "/dev/sdb1",
                "source_type": "blank",
                "destination_type": "local",
                "delete_on_termination": "True",
                "guest_format": "swap",
                "boot_index": "-1"
            },
            {
                "device_name": "/dev/sda1",
                "source_type": "volume",
                "destination_type": "volume",
                "uuid": "fake-volume-id-1",
                "boot_index": "0"
            }
        ]
```

So apparently we were wrong on several counts. First, it's not an element off the root, it's part of an object in an array nested under `block_device_mapping_v2`. Second, it's not required, or the example is invalid, because it was omitted on the second object in the example. Third, the example value shown is `True` rather than `true` as shown in the description. That may seem like a minor difference but it highlights that the type is ill-defined as `csapi:string`. It should be defined as a boolean if the service actually accepts one, or as an enum of valid string values.

If we look directly at the WADL we see it's slightly better, in that it tries to clarify the location in the hierarchy:
```xml
<param name="delete_on_termination"
                         style="plain"
                         type="csapi:string"
                         required="true"
                         path="$.parameters.block_device_mapping_v2.delete_on_termination">
                    <wadl:doc xmlns="http://docbook.org/ns/docbook" xml:lang="EN">
                        <para>To delete the boot volume when the server stops, specify
                     <code>true</code>. Otherwise, specify <code>false</code>.</para>
                     </wadl:doc>
                    </param>
```

However that path, which appears to be [jsonpath](http://goessner.net/articles/JsonPath/), is also wrong. It doesn't show that the root object should be named "server" or that `block_device_mapping_v2` contains an array. It should probably be something more like `$.servers.block_device_mapping_v2[*].delete_on_termination`, which would be better but defining paths this way will still be a lot more complex and ambiguous than using [json-schema](http://json-schema.org/).


So the problem is that these parameters are more like freeform documentation than a proper definition of the API. That means that:
1. 
Now, Swagger defines five parameter types in Swagger: path, query, header, body and form. I believe the generated WADL is complete except for body. I don't think any OpenStack services use "form" (it's for data that will be sent as `application/x-www-form-urlencode` or `multipart/form-data`), and I don't think any other types of parameters are missing.


In terms of proper Swagger here's what's actually missing is something like this, along with the corresponding schema:

```yaml
    post:
      parameters:
      - name: body
        in: body
        schema: $csapi:server
```

So, in terms of
